# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Виктория/AppData/Local/Temp/pro1fEGCKv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(False)
        MainWindow.resize(1130, 688)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setStyleSheet("*{\n"
"   border: none;\n"
"   background-color: transparent;\n"
"   background: none;\n"
"   padding: 0;\n"
"   margin: 0;\n"
"   color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: rgb(77, 80, 85);\n"
"}\n"
"#LeftMenuContainer {\n"
"    \n"
"    background-color: rgb(80, 70, 85);\n"
"}\n"
"#LeftMenuContainer QPushButton{\n"
"text-align:left;\n"
"padding: 15px 15px;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}\n"
"#frame_3{\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LeftMenuContainer = QtWidgets.QWidget(self.centralwidget)
        self.LeftMenuContainer.setEnabled(False)
        self.LeftMenuContainer.setMaximumSize(QtCore.QSize(55, 16777215))
        self.LeftMenuContainer.setStyleSheet("")
        self.LeftMenuContainer.setObjectName("LeftMenuContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LeftMenuContainer)
        self.verticalLayout.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.LeftMenuContainer)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MenuBtn = QtWidgets.QPushButton(self.frame)
        self.MenuBtn.setEnabled(False)
        self.MenuBtn.setStyleSheet("background-color: rgb(80, 70, 85);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/navigation.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MenuBtn.setIcon(icon)
        self.MenuBtn.setIconSize(QtCore.QSize(24, 24))
        self.MenuBtn.setCheckable(False)
        self.MenuBtn.setObjectName("MenuBtn")
        self.verticalLayout_3.addWidget(self.MenuBtn)
        self.HomeBtn = QtWidgets.QPushButton(self.frame)
        self.HomeBtn.setEnabled(False)
        self.HomeBtn.setStyleSheet("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(35, 40, 3, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/coffee.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeBtn.setIcon(icon1)
        self.HomeBtn.setIconSize(QtCore.QSize(24, 24))
        self.HomeBtn.setCheckable(False)
        self.HomeBtn.setAutoRepeat(False)
        self.HomeBtn.setAutoExclusive(False)
        self.HomeBtn.setAutoDefault(False)
        self.HomeBtn.setObjectName("HomeBtn")
        self.verticalLayout_3.addWidget(self.HomeBtn)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.LeftMenuContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.NewTaskBtn = QtWidgets.QPushButton(self.frame_2)
        self.NewTaskBtn.setStyleSheet("background-color: rgb(80, 70, 85);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/layers.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NewTaskBtn.setIcon(icon2)
        self.NewTaskBtn.setIconSize(QtCore.QSize(24, 24))
        self.NewTaskBtn.setObjectName("NewTaskBtn")
        self.verticalLayout_2.addWidget(self.NewTaskBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.HelpBtn = QtWidgets.QPushButton(self.frame_2)
        self.HelpBtn.setStyleSheet("background-color: rgb(80, 70, 85);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/mail.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HelpBtn.setIcon(icon3)
        self.HelpBtn.setIconSize(QtCore.QSize(24, 24))
        self.HelpBtn.setAutoDefault(True)
        self.HelpBtn.setObjectName("HelpBtn")
        self.verticalLayout_2.addWidget(self.HelpBtn)
        self.InformationBtn = QtWidgets.QPushButton(self.frame_2)
        self.InformationBtn.setEnabled(False)
        self.InformationBtn.setStyleSheet("background-color: rgb(80, 70, 85);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/monitor.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InformationBtn.setIcon(icon4)
        self.InformationBtn.setIconSize(QtCore.QSize(24, 24))
        self.InformationBtn.setObjectName("InformationBtn")
        self.verticalLayout_2.addWidget(self.InformationBtn)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_2.addWidget(self.LeftMenuContainer, 0, QtCore.Qt.AlignLeft)
        self.CenterMenuSubContainer = QtWidgets.QWidget(self.centralwidget)
        self.CenterMenuSubContainer.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CenterMenuSubContainer.sizePolicy().hasHeightForWidth())
        self.CenterMenuSubContainer.setSizePolicy(sizePolicy)
        self.CenterMenuSubContainer.setMouseTracking(True)
        self.CenterMenuSubContainer.setStyleSheet("")
        self.CenterMenuSubContainer.setObjectName("CenterMenuSubContainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.CenterMenuSubContainer)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.CenterMenuSubContainer)
        self.frame_3.setStyleSheet("background-color: rgb(80, 70, 85);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Home)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.Home)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.stackedWidget.addWidget(self.Home)
        self.Help = QtWidgets.QWidget()
        self.Help.setObjectName("Help")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Help)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.Help)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.Help)
        self.Info = QtWidgets.QWidget()
        self.Info.setObjectName("Info")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Info)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.Info)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.stackedWidget.addWidget(self.Info)
        self.NewTask = QtWidgets.QWidget()
        self.NewTask.setObjectName("NewTask")
        self.frame_7 = QtWidgets.QFrame(self.NewTask)
        self.frame_7.setGeometry(QtCore.QRect(20, 10, 971, 531))
        self.frame_7.setMouseTracking(True)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 391, 341))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_13.addWidget(self.label_17)
        self.label_19 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.label_19)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setTabletTracking(True)
        self.lineEdit_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setReadOnly(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_13.addWidget(self.lineEdit_7)
        self.label_20 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_13.addWidget(self.label_20)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_13.addWidget(self.lineEdit_6)
        self.label_21 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_13.addWidget(self.label_21)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_13.addWidget(self.lineEdit_5)
        self.OkBtn = QtWidgets.QPushButton(self.frame_7)
        self.OkBtn.setGeometry(QtCore.QRect(400, 310, 101, 31))
        self.OkBtn.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(0, 0, 0);")
        self.OkBtn.setObjectName("OkBtn")
        self.HumansPerHour = QtWidgets.QLineEdit(self.frame_7)
        self.HumansPerHour.setEnabled(False)
        self.HumansPerHour.setGeometry(QtCore.QRect(420, 100, 331, 18))
        self.HumansPerHour.setTabletTracking(True)
        self.HumansPerHour.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.HumansPerHour.setStyleSheet("QLineEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit.hover{\n"
"    border: 2px add rgb(85, 255, 255);\n"
"}\n"
"\n"
"QLineEdit.focus {\n"
"    border: 2px add rgb(85, 255, 255);    \n"
"}")
        self.HumansPerHour.setText("")
        self.HumansPerHour.setObjectName("HumansPerHour")
        self.HumansPerHour.raise_()
        self.frame_8.raise_()
        self.OkBtn.raise_()
        self.stackedWidget.addWidget(self.NewTask)
        self.NewTask2 = QtWidgets.QWidget()
        self.NewTask2.setObjectName("NewTask2")
        self.frame_9 = QtWidgets.QFrame(self.NewTask2)
        self.frame_9.setGeometry(QtCore.QRect(0, 10, 961, 641))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setEnabled(False)
        self.frame_10.setGeometry(QtCore.QRect(10, 20, 511, 461))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_33 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_16.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_16.addWidget(self.label_34)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit.setStyleSheet("\n"
"QLineEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_16.addWidget(self.lineEdit)
        self.label_37 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_16.addWidget(self.label_37)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_16.addWidget(self.lineEdit_2)
        self.label_35 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_16.addWidget(self.label_35)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_16.addWidget(self.lineEdit_3)
        self.label_38 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_16.addWidget(self.label_38)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_16.addWidget(self.lineEdit_4)
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_16.addWidget(self.label_2)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_10.setStyleSheet("QLineEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_16.addWidget(self.lineEdit_10)
        self.label_39 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_16.addWidget(self.label_39)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_11.setStyleSheet("QLineEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_16.addWidget(self.lineEdit_11)
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_16.addWidget(self.label_3)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_9.setStyleSheet("QLineEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_16.addWidget(self.lineEdit_9)
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_16.addWidget(self.label_6)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_12.setStyleSheet("QLineEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_16.addWidget(self.lineEdit_12)
        self.textEdit = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit.setGeometry(QtCore.QRect(553, 40, 381, 451))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    border: 2px add rgb(255, 0, 0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.stackedWidget.addWidget(self.NewTask2)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.CenterMenuSubContainer)
        self.mainBodyCotntainer = QtWidgets.QWidget(self.centralwidget)
        self.mainBodyCotntainer.setObjectName("mainBodyCotntainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainBodyCotntainer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addWidget(self.mainBodyCotntainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.HumansPerHour.textEdited['QString'].connect(self.HumansPerHour.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SmartBubble"))
        self.MenuBtn.setToolTip(_translate("MainWindow", "Menu"))
        self.MenuBtn.setText(_translate("MainWindow", "Menu"))
        self.HomeBtn.setToolTip(_translate("MainWindow", "Home"))
        self.HomeBtn.setText(_translate("MainWindow", "Home"))
        self.NewTaskBtn.setToolTip(_translate("MainWindow", "New task"))
        self.NewTaskBtn.setText(_translate("MainWindow", "New task"))
        self.HelpBtn.setToolTip(_translate("MainWindow", "Help"))
        self.HelpBtn.setText(_translate("MainWindow", "Help"))
        self.InformationBtn.setToolTip(_translate("MainWindow", "Information"))
        self.InformationBtn.setText(_translate("MainWindow", "Information"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Добро пожаловать в SmartBubble </span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Чтобы начать работу, нажмите &quot;New task&quot; в меню слева.</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Если вы впервые работаете в этой программе, выберите пункт &quot;information&quot;, чтобы ознакомиться с основными функциями.</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Если у вас возникли трудности или вы хотите предложить идеи по улучшению SmartBubble, воспользуйтесь пунктом меню &quot;Help&quot;.</span></p><p align=\"center\"><span style=\" font-size:9pt;\"><br/></span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Контактная информация для обратной связи и поддержки пользователей:</span></p><p align=\"center\"><span style=\" font-weight:600;\"><br/><br/></span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Если у вас возникли вопросы по использованию SmartBubble, пожалуйста, <br/>свяжитесь с нашей службой поддержки по электронной почте support_smartbubble@mail.com. </span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Мы приложим все усилия, чтобы ответить на ваш запрос в течение 24 часов.</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Отзывы и предложения по улучшению SmartBubble:</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Мы всегда рады отзывам и предложениям от наших пользователей, которые помогают нам улучшить сервис SmartBubble.</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Если у вас есть какие-либо идеи или предложения по улучшению нашего сервиса, </span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">пожалуйста, напишите нам по адресу feedback_smartbubble@mail.com. </span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Мы обязательно рассмотрим ваше предложение и ответим на ваше сообщение в течение нескольких дней.</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Благодарим вас за участие в улучшении SmartBubble!</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">SmartBubble - это прикладное программное обеспечение,<br/>основанное на теории массового обслуживания, <br/>предназначенное для оптимизации работы автомоек. <br/>С помощью SmartBubble пользователь вводит необходимы еданные, <br/>и программа рассчитывает различные показатели <br/>эффективности системы, такие как вероятность <br/>простоя системы и среднюю длину очереди. Кроме <br/>того, SmartBubble предоставляет рекомендации по <br/>улучшению процесса раюоты автомойки, основываясь на <br/>полученных данных. Благодаря этому программному <br/>обеспечению владельцы автомоек могут <br/>оптимизировать свою работу, повышая качество <br/>обслуживания и эффективность автомойки.</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Пожалуйста, введите данные о вашей автомойке</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "Среднее кол-во посетителей в час"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "hi"))
        self.label_20.setText(_translate("MainWindow", "Кол-во каналов обслуживания"))
        self.label_21.setText(_translate("MainWindow", "Интенсивность обслуживания"))
        self.OkBtn.setToolTip(_translate("MainWindow", "Рассчитать"))
        self.OkBtn.setText(_translate("MainWindow", "OK"))
        self.HumansPerHour.setPlaceholderText(_translate("MainWindow", "Hello"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Рассчитанные показатели и рекомендации</p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "Вероятность простоя системы"))
        self.label_37.setText(_translate("MainWindow", "Средняя длина очереди"))
        self.label_35.setText(_translate("MainWindow", "Среднее время ожидая в очереди"))
        self.label_38.setText(_translate("MainWindow", "Нагрузка системы"))
        self.label_2.setText(_translate("MainWindow", "Вероятность образования очереди"))
        self.label_39.setText(_translate("MainWindow", "Среднее число занятых каналов"))
        self.label_3.setText(_translate("MainWindow", "Среднее число требований в системе"))
        self.label_6.setText(_translate("MainWindow", "Среднее время прибывания в системе"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Franklin Gothic Medium\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt;\">sadads</span></p></body></html>"))
import resources_rc
